name: locan
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alabaster=0.7.13=pyhd8ed1ab_0
  - alsa-lib=1.2.10=hd590300_0
  - aom=3.6.1=h59595ed_0
  - app-model=0.2.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asciitree=0.3.3=py_2
  - asdf=2.15.1=pyhd8ed1ab_0
  - asdf-standard=1.0.3=pyhd8ed1ab_0
  - asdf-transform-schemas=0.3.0=pyhd8ed1ab_0
  - asdf-unit-schemas=0.1.0=pyhd8ed1ab_0
  - asteval=0.9.31=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blosc=1.21.5=h0f2a231_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boost-histogram=1.4.0=py310hd41b1e2_1
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - c-blosc2=2.10.2=hb4ffafa_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachey=0.2.1=pyh9f0ad1d_0
  - cairo=1.16.0=h0c91306_1017
  - certifi=2023.7.22=pyhd8ed1ab_0
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.3.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.0.1=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.1.1=py310hd41b1e2_1
  - cycler=0.12.0=pyhd8ed1ab_0
  - cython=3.0.2=py310hc6cd4ac_2
  - cytoolz=0.12.2=py310h2372a71_1
  - dask=2023.3.0=pyhd8ed1ab_0
  - dask-core=2023.3.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.0=py310hc6cd4ac_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2023.3.0=pyhd8ed1ab_0
  - docstring_parser=0.15=pyhd8ed1ab_0
  - docutils=0.17.1=py310hff52083_4
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fast-histogram=0.11=py310h1f7b6fc_2
  - fasteners=0.17.3=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.43.0=py310h2372a71_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.4.0=pyhd8ed1ab_0
  - fsspec=2023.9.2=pyh1a96a4e_0
  - future=0.18.3=pyhd8ed1ab_0
  - geos=3.11.1=h27087fc_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - glib=2.78.0=hfc55251_0
  - glib-tools=2.78.0=hfc55251_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.6=h8e1006c_2
  - gstreamer=1.22.6=h98fc4e7_2
  - h5py=3.9.0=nompi_py310ha2ad45a_103
  - harfbuzz=8.2.1=h3d44ed6_0
  - hdbscan=0.8.33=py310h1f7b6fc_3
  - hdf5=1.14.2=nompi_h4f84152_100
  - heapdict=1.0.1=py_0
  - hsluv=5.0.4=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2023.9.18=py310h3a85d3a_0
  - imageio=2.31.1=pyh24c5eb1_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib-resources=6.1.0=pyhd8ed1ab_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - in-n-out=0.1.8=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.25.2=pyh2140261_0
  - ipython=8.16.1=pyh0d859eb_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jsonschema=4.19.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.2=py310hff52083_0
  - jxrlib=1.1=h7f98852_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lazy_loader=0.3=pyhd8ed1ab_0
  - lcms2=2.15=h7f713cb_2
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.2=h59595ed_1
  - libavif16=1.0.1=h87da1f6_2
  - libblas=3.9.0=18_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=18_linux64_openblas
  - libclang=15.0.7=default_h7634d5b_3
  - libclang13=15.0.7=default_h9986a30_3
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.3.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_2
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_2
  - libgpg-error=1.47=h71f35ed_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=18_linux64_openblas
  - libllvm15=15.0.7=h5cf9203_3
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=hd590300_1
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.4=hfc447b1_2
  - libprotobuf=4.24.3=hf27288f_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.43.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libsystemd0=254=h3516f8a_0
  - libtiff=4.6.0=h29866fb_1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.5.0=h5d7e998_3
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - libzopfli=1.0.3=h9c3ff4c_0
  - lmfit=1.2.2=pyhd8ed1ab_1
  - locket=1.0.0=pyhd8ed1ab_0
  - looseversion=1.3.0=pyhd8ed1ab_0
  - lz4=4.3.2=py310h350c4a5_1
  - lz4-c=1.9.4=hcb278e6_0
  - magicgui=0.7.3=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py310h2372a71_1
  - matplotlib=3.7.3=py310hff52083_0
  - matplotlib-base=3.7.3=py310h62c0568_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mpg123=1.32.3=h59595ed_0
  - mpl-scatter-density=0.7=pyhd8ed1ab_0
  - msgpack-python=1.0.6=py310hd41b1e2_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.0.33=hf1915f5_4
  - mysql-libs=8.0.33=hca2cd23_4
  - napari=0.4.18=pyhd8ed1ab_2
  - napari-console=0.0.8=pyhd8ed1ab_0
  - napari-plugin-engine=0.2.0=pyhd8ed1ab_2
  - napari-svg=0.1.10=pyhd8ed1ab_0
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - npe2=0.7.2=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.94=h1d7d5a4_0
  - numcodecs=0.11.0=py310heca2aa9_1
  - numpy=1.26.0=py310hb13e2d6_0
  - numpydoc=1.5.0=pyhd8ed1ab_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=3.1.3=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.1=py310hcc13569_1
  - param=1.13.0=pyh1a96a4e_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py310h29da1c1_1
  - pint=0.22=pyhd8ed1ab_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyhd8ed1ab_4
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - protobuf=4.24.3=py310h620c231_0
  - psutil=5.9.5=py310h2372a71_1
  - psygnal=0.9.4=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio-client=16.1=hb77b528_5
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pydantic=1.10.13=py310h2372a71_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyopengl=3.1.6=pyhd8ed1ab_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.2=pyhd8ed1ab_0
  - python=3.10.12=hd12c33a_0_cpython
  - python-build=1.0.3=pyhd8ed1ab_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywavelets=1.4.1=py310h1f7b6fc_1
  - pyyaml=6.0.1=py310h2372a71_1
  - pyzmq=25.1.1=py310h5bbb5d0_1
  - qt-main=5.15.8=hc47bfe8_16
  - qtconsole-base=5.4.4=pyha770c72_0
  - qtpy=2.4.0=pyhd8ed1ab_0
  - rav1e=0.6.6=he8a937b_2
  - readline=8.2=h8228510_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.6.0=pyhd8ed1ab_0
  - rpds-py=0.10.3=py310hcb5633a_1
  - ruamel.yaml=0.17.35=py310h2372a71_0
  - ruamel.yaml.clib=0.2.7=py310h2372a71_2
  - scikit-image=0.21.0=py310hc6cd4ac_0
  - scikit-learn=1.3.1=py310h1fdf081_0
  - scipy=1.11.3=py310hb13e2d6_1
  - semantic_version=2.10.0=pyhd8ed1ab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - setuptools-scm=8.0.4=pyhd8ed1ab_0
  - shapely=1.8.5=py310h5b266fc_2
  - shellingham=1.5.3=pyhd8ed1ab_0
  - sip=6.7.11=py310hc6cd4ac_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sphinx=4.5.0=pyh6c4a22f_0
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - stack_data=0.6.2=pyhd8ed1ab_0
  - superqt=0.6.0=pyh9208f05_0
  - svt-av1=1.7.0=h59595ed_0
  - tblib=2.0.0=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tifffile=2023.9.26=pyhd8ed1ab_0
  - tk=8.6.13=h2797004_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomli-w=1.0.0=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.3=py310h2372a71_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - trackpy=0.6.1=pyhd8ed1ab_0
  - traitlets=5.11.2=pyhd8ed1ab_0
  - typer=0.9.0=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - uncertainties=3.1.7=pyhd8ed1ab_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - urllib3=2.0.6=pyhd8ed1ab_0
  - vispy=0.12.2=py310hcbf0ad0_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - wrapt=1.15.0=py310h2372a71_1
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.39=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zarr=2.16.1=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=1.0.0=h59595ed_4
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - addict==2.4.0
      - ansi2html==1.8.0
      - configargparse==1.7
      - dash==2.13.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - fastjsonschema==2.18.1
      - flask==2.2.5
      - ipywidgets==8.1.1
      - itsdangerous==2.1.2
      - jupyterlab-widgets==3.0.9
      - nbformat==5.7.0
      - open3d==0.17.0
      - plotly==5.17.0
      - pyquaternion==0.9.9
      - retrying==1.3.4
      - tenacity==8.2.3
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.9
prefix: /usr/share/miniconda3/envs/locan
